kind: ConfigMap
apiVersion: v1
metadata:
  name: gen-ai-aa-mcp-servers
  namespace: redhat-ods-applications
immutable: false
data:
{{- range .Values.mcpServers }}
  {{ .id }}-MCP-Server: |
      {
      "url": "{{ .protocol }}://{{ .host }}.{{ $.Release.Namespace }}:{{ .port }}{{ .uri }}",
      "description": "{{ .description }}",
      "transport": "{{ .mcp_transport }}"
      }
{{- end }}